
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.*;
import ventanas.*;
import usuario.*;
import BD.mongo.*;


@SuppressWarnings("serial")
public class VentanaRegistrar extends JFrame {

    /**
     * Creates new form VentanaRegistrar
     */
    public VentanaRegistrar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @Override
        public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        jbEntrar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jtNombre = new javax.swing.JTextField();
        jtApellidos = new javax.swing.JTextField();
        jtUser = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jpContrasena = new javax.swing.JPasswordField();
        jpConfirmacion = new javax.swing.JPasswordField();
        jtCiudad = new javax.swing.JTextField();
        jtTwitter = new javax.swing.JTextField();
        jtFacebook = new javax.swing.JTextField();
        jdNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbAtras = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WorldWifi");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(610, 770));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(610, 770));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbEntrar.setBackground(new java.awt.Color(51, 153, 255));
        jbEntrar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jbEntrar.setText("Entrar");
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 160, 60));

        jbSalir.setBackground(new java.awt.Color(51, 153, 255));
        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Salir");
        jbSalir.setActionCommand("jbSalir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 70, -1));

        jtNombre.setBackground(new java.awt.Color(204, 204, 204));
        jtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtNombre.setForeground(new java.awt.Color(255, 255, 255));
        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 150, 30));

        jtApellidos.setBackground(new java.awt.Color(204, 204, 204));
        jtApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(jtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 150, 30));

        jtUser.setBackground(new java.awt.Color(204, 204, 204));
        jtUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtUser.setForeground(new java.awt.Color(255, 255, 255));
        jtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUserActionPerformed(evt);
            }
        });
        getContentPane().add(jtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 150, 30));

        jtCorreo.setBackground(new java.awt.Color(204, 204, 204));
        jtCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(jtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 150, 30));

        jpContrasena.setBackground(new java.awt.Color(204, 204, 204));
        jpContrasena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpContrasena.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jpContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 150, 30));

        jpConfirmacion.setBackground(new java.awt.Color(204, 204, 204));
        jpConfirmacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jpConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 150, 30));

        jtCiudad.setBackground(new java.awt.Color(204, 204, 204));
        jtCiudad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtCiudad.setForeground(new java.awt.Color(255, 255, 255));
        jtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(jtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 150, 30));

        jtTwitter.setBackground(new java.awt.Color(204, 204, 204));
        jtTwitter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtTwitter.setForeground(new java.awt.Color(255, 255, 255));
        jtTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTwitterActionPerformed(evt);
            }
        });
        getContentPane().add(jtTwitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 150, 30));

        jtFacebook.setBackground(new java.awt.Color(204, 204, 204));
        jtFacebook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtFacebook.setForeground(new java.awt.Color(255, 255, 255));
        jtFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFacebookActionPerformed(evt);
            }
        });
        getContentPane().add(jtFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 150, 30));

        jdNacimiento.setBackground(new java.awt.Color(204, 204, 204));
        jdNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        jdNacimiento.setMaxSelectableDate(jdNacimiento.getDate());
        jdNacimiento.setMinSelectableDate(new java.util.Date(-2208985668000L));
        getContentPane().add(jdNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nacimiento:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ciudad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Twitter");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Facebook");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        jbAtras.setBackground(new java.awt.Color(51, 153, 255));
        jbAtras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbAtras.setForeground(new java.awt.Color(255, 255, 255));
        jbAtras.setText("Atras");
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jbAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 120, 40));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1389718468_water-drops-on-a-window_ipad.jpg"))); // NOI18N

	

        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 790));


        pack();
    }// </editor-fold>                        

    public com.toedter.calendar.JDateChooser getJdNacimiento() {
		return jdNacimiento;
	}

	public void setJdNacimiento(com.toedter.calendar.JDateChooser jdNacimiento) {
		this.jdNacimiento = jdNacimiento;
	}

	public javax.swing.JPasswordField getJpContrasena() {
		if (jpContrasena == jpConfirmacion){
			return jpContrasena;
		}
		return null;
	}

	public void setJpContrasena(javax.swing.JPasswordField jpContrasena) {
		this.jpContrasena = jpContrasena;
	}

	public javax.swing.JTextField getJtApellidos() {
		return jtApellidos;
	}

	public void setJtApellidos(javax.swing.JTextField jtApellidos) {
		this.jtApellidos = jtApellidos;
	}

	public javax.swing.JTextField getJtCiudad() {
		return jtCiudad;
	}

	public void setJtCiudad(javax.swing.JTextField jtCiudad) {
		this.jtCiudad = jtCiudad;
	}

	public javax.swing.JTextField getJtCorreo() {
		return jtCorreo;
	}

	public void setJtCorreo(javax.swing.JTextField jtCorreo) {
		this.jtCorreo = jtCorreo;
	}

	public javax.swing.JTextField getJtFacebook() {
		return jtFacebook;
	}

	public void setJtFacebook(javax.swing.JTextField jtFacebook) {
		this.jtFacebook = jtFacebook;
	}

	public javax.swing.JTextField getJtNombre() {
		return jtNombre;
	}

	public void setJtNombre(javax.swing.JTextField jtNombre) {
		this.jtNombre = jtNombre;
	}

	public javax.swing.JTextField getJtTwitter() {
		return jtTwitter;
	}

	public void setJtTwitter(javax.swing.JTextField jtTwitter) {
		this.jtTwitter = jtTwitter;
	}

	public javax.swing.JTextField getJtUser() {
		return jtUser;
	}

	public void setJtUser(javax.swing.JTextField jtUser) {
		this.jtUser = jtUser;
	}

	public void setTipo(){
		
	}
	private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if( !ConectarMongo.userExists(jtUser.getText())  && jpConfirmacion.getPassword() == jpContrasena.getPassword()
    		   && jtCorreo.getText() != SistemaUsuarios.this.grupoUsuarios.g ){
    	   ConectarMongo.createUser(jtUser.getText());
    	   VentanaInicio a = new VentanaInicio();
    	   a.setVisible(true);
    	   this.setVisible(false);
        }
    }                                        

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {                                        
        System.exit(0);
    }                                       

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {                                        
 	   VentanaInicio a = new VentanaInicio();
 	   a.setVisible(true);
 	   this.setVisible(false);
    }                                       

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {                                         
    }                                        

    private void jtApellidosActionPerformed(java.awt.event.ActionEvent evt) {                                            

    }                                           

    private void jtUserActionPerformed(java.awt.event.ActionEvent evt) {                                       

    }                                      

    private void jtCorreoActionPerformed(java.awt.event.ActionEvent evt) {                                         

    }                                        

    private void jtFacebookActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    private void jtCiudadActionPerformed(java.awt.event.ActionEvent evt) {                                         
     
    }                                        

    private void jtTwitterActionPerformed(java.awt.event.ActionEvent evt) {                                          
     
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JButton jbSalir;
    private com.toedter.calendar.JDateChooser jdNacimiento;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JPasswordField jpConfirmacion;
    private javax.swing.JPasswordField jpContrasena;
    private javax.swing.JTextField jtApellidos;
    private javax.swing.JTextField jtCiudad;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtFacebook;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTwitter;
    private javax.swing.JTextField jtUser;
    // End of variables declaration                   
}
